#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 27 13:47:03 2018

@author: abdulsamad
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


from sklearn.preprocessing import Imputer

dataset = pd.read_csv('Salary_Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,1].values


# training and test sample data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

from sklearn.linear_model import LinearRegression
linearRegression = LinearRegression(fit_intercept = True, normalize = True)
linearRegression.fit(X_train, y_train)
predictions = linearRegression.predict(X_test)

#visulize data
plt.scatter(X_train, y_train, c = 'blue')
plt.scatter(X_test, predictions, c = 'green')
plt.scatter(X_test, y_test, c = 'yellow')
plt.plot(X_train, linearRegression.predict(X_train), c = 'red')
plt.title('Salary vs Experience in years')
plt.xlabel('Expenience')
plt.ylabel('Salary')
plt.plot()
